name: Publish package to GitHub Packages
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: mvn -B package --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
